---
title: "DO1200"
author: "Brian Yandell"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a reframing of DO1200 data to use with 
[qtl2shiny](https://github.com/byandell-sysgen/qtl2shiny).
See
[Recla.Rmd](Recla.Rmd)
for prototype analysis with Recla et al. dataset.
See
[DO1200Data.Rmd](DO1200Data.Rmd)
for code to set up data.

```{r}
(project_info <- data.frame(project = "DO1200",
                           taxa = "CCmouse",
                           directory = "qtl2shinyData"))
```

## Key Summary Information


```{r}
project <- project_info$project
project_path <- paste(rev(project_info), collapse = "/")
window_Mbp <- 1
```

```{r}
dataset_name <- "plasma_metabolites_13C"
```

```{r}
read_peakset <- function(project_info, 
  dataset_name = c("clinical_traits", "liver_genes", "liver_isoforms", "liver_lipids",
                   "liver_psi", "liver_splice_juncs", "plasma_metabolites",
                   "plasma_metabolites", "plasma_metabolites_13C", "plasma_metabolites_2H"),
  dietset = c("all", "HC", "HF", "male", "female"),
  intset = c("additive", "diet_interactive", "sex_interactive")) {
  
  dataset_name <- match.arg(dataset_name)
  if(dataset_name == "liver_psi") dataset_name <- "liver_splice_juncs"
  if(dataset_name %in% c("plasma_metabolites_13C", "plasma_metabolites_2H"))
    dataset_name <- "plasma_metabolites"
  dietset <- match.arg(dietset)
  intset <- match.arg(intset)
  
  peakset_file <- paste("DO1200", dataset_name, dietset, "mice", intset,
                        "peaks.rds", sep = "_")

  readRDS(file.path(project_path, "peaks", peakset_file)) |>
    dplyr::select(-Which_mice)
}
peaks <- read_peakset(project_info, dataset_name)
```

```{r}
(argpeak <- peaks |>
  dplyr::filter(grepl("AUC_ARG", phenotype))) |>
  dplyr::select(phenotype, qtl_lod, qtl_chr, qtl_pos)
```

```{r}
read_dataset <- function(project_info, dataset_name) {
  project_path <- paste(rev(project_info), collapse = "/")
  readRDS(file.path(project_path, paste0("pheno_", dataset_name, ".rds")))
}
pheno_data <- read_dataset(project_info, "plasma_metabolites_13C")
```

```{r}
names(pheno_data)[grep("AUC_ARG", names(pheno_data))]
```

```{r}
pheno_name <- argpeak$phenotype
chr_id <- as.character(argpeak$qtl_chr)
peak_Mbp <- argpeak$qtl_pos
addcovar <- argpeak$addcovar
intcovar <- argpeak$intcovar
window_Mbp <- 1
```

```{r}
phe_mx <- pheno_data[,grep(pheno_name, colnames(pheno_data)), drop = FALSE]
covar <- qtl2shiny:::read_project(project_info, "covar")
cov_df <- model.matrix(formula(addcovar), covar)
K_chr <- qtl2shiny:::read_project(project_info, "kinship_local")[chr_id]
# Following used for mediation.
pmap_obj <- qtl2shiny:::read_project(project_info, "pmap")
```

## Haplotype Server

```{r}
sex_type <- "A"
```

```{r}
start_val <- peak_Mbp - window_Mbp
end_val <- peak_Mbp + window_Mbp
# Define query_probs function
query_probs <- qtl2shiny:::read_query_rds(project_info, "query_probs.rds")
# Note probs object keeps map with it
probs_obj <- query_probs(chr_id, start_val, end_val)
```

### Small region scan

This needs to be redone, walking through `qtl2mediate::scan1covar`.
Probably a new function `qtl2shiny::scan1covar`.

```{r}
scan_obj <- qtl2mediate::scan1covar(phe_mx, cov_df, probs_obj$probs, K_chr,
                                    analyses_df, sex_type = sex_type)
```